export const MAIN_MENU = {
  PLOT_AVAILABILITY: "PLOT AVAILABILITY",
  VIEW_POLLED_AVAILABILITIES: "VIEW POLLED AVAILABILITIES",
};

export const PLOT_AVAILABILITY_SUB = {
  ADD: "ADD",
  REMOVE: "REMOVE",
};

export const VIEW_POLLED_AVAILABILITIES_SUB = {
  GRID_VIEW: "GRID VIEW",
  BAR_GRAPH: "BAR GRAPH",
};
